# Generated by Django 4.2.7 on 2023-12-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
